myapi/urls.py
#myapi/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'), 
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',
         views.AuthorDetailView.as_view(), name='author-detail'),
    path('listauthor/', views.listauthor),
    path('addauthor/', views.authorview)     
    
]

myapi/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    ISBN = models.CharField(max_length=60)
    Title = models.CharField(max_length=60)
    Description = models.CharField(max_length=60)
    PublishDate = models.DateField()

    def __str__(self):
        return self.Title


class Genre(models.Model):
    GenreID = models.CharField(max_length=60)
    Type = models.CharField(max_length=60)

    def __str__(self):
        return self.Type


class Publisher(models.Model):
    PublisherID = models.CharField(max_length=60)
    Name = models.CharField(max_length=60)

    def __str__(self):
        return self.Name


class Author(models.Model):
    AuthorID = models.CharField(max_length=60)
    FName = models.CharField(max_length=60)
    LName = models.CharField(max_length=60)
    Biography = models.CharField(max_length=60)

    class Meta:
        ordering = ['LName', 'FName']

    def get_absolute_url(self):

        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.LName, self.FName)


class BookDetails(models.Model):
    ID = models.CharField(max_length=60)
    Price = models.CharField(max_length=60)
    CopiesSold = models.CharField(max_length=60)
    ISBN = models.ForeignKey(Book, on_delete=models.CASCADE)
    GenreID = models.ForeignKey(Genre, on_delete=models.CASCADE)
    PublisherID = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    AuthorID = models.ForeignKey(Author, on_delete=models.CASCADE)

    class Meta:
        ordering = ['ISBN', 'AuthorID']

    def display_genre(self):
        return ', '.join([genre.type for genre in (self.genre, all()[:3])])

    display_genre.short_description = 'Genre'

myapi/views.py
from django.shortcuts import render
from .models import BookDetails
from .models import Book
from .models import Genre
from .models import Publisher
from .models import Author
from django.shortcuts import render
from .models import *
from .serializers import *
from django.db.models.aggregates import Avg
from django.db.models.query import QuerySet
from django.utils.html import avoid_wrapping
from .forms import *
from .models import Book, BookRating
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.signals import post_save
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics, response
from rest_framework.parsers import JSONParser
from typing import ContextManager
from myapi import serializers
import json
from django.shortcuts import render, redirect
from .models import Order, OrderItem
from .models import BookDetails
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import APIView

def index(request):
    num_books = Book.objects.all().count() 
    num_authors = Author.objects.count()  

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1


    return render(
        request,
        'index.html',
        context={'num_books': num_books, 'num_authors': num_authors,
                 'num_visits': num_visits},
    )
    
from django.views import generic


class AuthorListView(generic.ListView):
    """Generic class-based list view for a list of authors."""
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    """Generic class-based detail view for an author."""
    model = Author

class BookListView(generic.ListView):
    """Generic class-based view for a list of books."""
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    """Generic class-based detail view for a book."""
    model = Book

def listauthor(request):
    if request.method == "GET":
        authors = Author.objects.all()
        serializer = authorserializer(authors, many=True)
        return JsonResponse(serializer.data, safe=False)


@csrf_exempt
def authorview(request):
    form = AddAuthor()
    if request.method == "POST":
        if form.is_valid():
            form = AddAuthor(request.POST)
            Author = form.save(commit=False)
            Author.save()


    context = {'form': form}
    return render(request, 'myapi/author_detail.html', context)    

myapi/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'authors' %}">All authors</a></li>
  </ul>

{% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}
  
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  
  
  </div>
</div>

</div>
</body>
</html>

myapi/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
<li><strong>Books:</strong> {{ num_books }}</li>
<li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>


<p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>

{% endblock %}

myapi/templates/myapi/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author: {{ author }} </h1>
<p>{{author.biography}}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in author.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

myapi/templates/myapi/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.AuthorID}}
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
        
        
        
{% endblock %}

myapi/templates/myapi/bookratings.html
{%load crispy_forms_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %} 

            <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{user.username}}</a>
            </li>

            {% else %} 

            <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
            </li>

            {% endif %} 

        </ul>
    </div>
</nav>

{% block content %}
<h3>Rate a Book!</h3>
<h1>We'd love to know your thoughts.</h1>
<form method = "POST">
    {% csrf_token %}
    {{form|crispy}}
    <input type = 'submit' value = 'Save' />
</form>

{% endblock %} 

myapi/templates/myapi/login.html
{% extends "base.html" %}

{% block title %}Log In{% endblock title %}

{% block content %}

<h3>Log In</h3>

<form method = "post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit" class = 'btn btn-success'>Log In</button>
    <a class = "btn btn-outline-info" href = "{% url 'signup' %}" role = "button">Create Account</a>    
</form>


{% endblock content %}

myapi/templates/register.html
<h3>Register</h3>

<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="Create Profile">
</form>